export const CSS_CLASSES = {
	hidden: "smartyAddress__hidden",
	matchedText: "smartyAddress__matchedText",
	smartyLogoDark: "smartyAddress__smartyLogoDark",
	smartyLogoLight: "smartyAddress__smartyLogoLight",
	autocompleteSuggestionsElement: "smartyAddress__autocompleteSuggestionsElement",
	poweredBy: "smartyAddress__poweredBy",
	dropdownElement: "smartyAddress__dropdownElement",
	autocompleteSuggestionsWrapperElement: "smartyAddress__autocompleteSuggestionsWrapperElement",
	srOnly: "smartyAddress__srOnly",
	autocompleteAddress: "smartyAddress__autocompleteAddress",
	addressWrapper: "smartyAddress__addressWrapper",
	autocompleteSuggestionEntries: "smartyAddress__autocompleteSuggestionEntries",
	autocompleteSuggestion: "smartyAddress__autocompleteSuggestion",
	secondaryAutocompleteSuggestion: "smartyAddress__secondaryAutocompleteSuggestion",
	entriesChevron: "smartyAddress__entriesChevron",
	entriesChevronUp: "smartyAddress__entriesChevronUp",
	showAllSecondaries: "smartyAddress__showAllSecondaries",
	colorDynamic: "smartyAddress__color_dynamic",
	positionDynamic: "smartyAddress__position_dynamic",

	verifyVars: "smartyAddress__verify_default",
	verifyAnnouncer: "smartyAddress__verifyAnnouncer",
	verifyBadge: "smartyAddress__verifyBadge",
	verifyBadgePositive: "smartyAddress__verifyBadge_positive",
	verifyBadgeWarning: "smartyAddress__verifyBadge_warning",
	verifyBadgeNegative: "smartyAddress__verifyBadge_negative",
	verifyPanel: "smartyAddress__verifyPanel",
	verifyPanelMessage: "smartyAddress__verifyPanelMessage",
	verifyChooser: "smartyAddress__verifyChooser",
	verifyChooserOption: "smartyAddress__verifyChooserOption",
} as const;

export const CSS_PREFIXES = {
	instance: "smartyAddress__instance_",
	dropdown: "smartyAddress__dropdown_",
	autocompleteSuggestion: "smartyAddress__autocompleteSuggestion_",
} as const;
